Global("debugMode", true)

Global("COLOR_IMPOSSIBLE", "ffC41E3A")
Global("COLOR_BAD", "ffFF7C0A")
Global("COLOR_SECOND", "ffFFF468")
Global("COLOR_GOOD", "ffA330C9")
Global("COLOR_NORMAL", "ffFFFFFF")
Global("COLOR_AOE", "ff00FF98")
Global("COLOR_DEF", "ffC69B6D")
Global("COLOR_DOT", "ff8788EE")
Global("COLOR_TRINKET", "ff3FC7EB")
Global("COLOR_NONE","COLOR_NONE")
Global("COLOR_BUFF","ffC69B6D")
